# In auth-service/.github/workflows/ci-cd.yml
name: Auth Service CI (Build, Push, Update Manifest)

on:
  push:
    branches:
      - main # Or your primary branch
  workflow_dispatch:

jobs:
  build-and-update-manifest:
    runs-on: ubuntu-latest
    env:
      # Docker and Image Configuration
      DOCKER_IMAGE_NAME: mariuspreda/auth-service
      
      # Deployment Repository Configuration
      DEPLOYMENT_REPO_OWNER_SLASH_NAME: IDP-Project-Kindergarten-Companion/deployment
      # Path to the K8s deployment YAML for this service WITHIN the 'deployment' repository
      K8S_MANIFEST_PATH_IN_DEPLOY_REPO: k8s/core-services/auth/auth-service-k8s.yaml
      # Name of the container within your K8s deployment manifest for this service
      K8S_CONTAINER_NAME: auth-service-container 

    steps:
      - name: Checkout auth-service source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Docker Hub PAT

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: . # Build from the root of the auth-service repo
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} # Tag with commit SHA
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Checkout Deployment Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.DEPLOYMENT_REPO_OWNER_SLASH_NAME }}
          path: deployment-repo # Checkout to a specific path
          token: ${{ secrets.PAT_FOR_DEPLOYMENT_REPO }} # GitHub PAT with repo scope

      - name: Update Kubernetes Deployment Manifest with new image tag
        run: |
          DEPLOYMENT_FILE_FULL_PATH="deployment-repo/${{ env.K8S_MANIFEST_PATH_IN_DEPLOY_REPO }}"
          NEW_IMAGE_WITH_TAG="${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}"
          
          echo "Updating image in Kubernetes manifest '${DEPLOYMENT_FILE_FULL_PATH}' to '${NEW_IMAGE_WITH_TAG}'"
          
          # Using sed to update the image tag. 
          # This sed command targets the image line for the specified container name.
          # Adjust K8S_CONTAINER_NAME if your container name in the YAML is different.
          sed -i.bak -E "s|(\s*-\s*name:\s*${K8S_CONTAINER_NAME}\s*.*?image:\s*)${{ env.DOCKER_IMAGE_NAME }}:.*|\1${NEW_IMAGE_WITH_TAG}|" "${DEPLOYMENT_FILE_FULL_PATH}"
          
          # Verify the change (optional, good for debugging)
          echo "Updated manifest content:"
          cat "${DEPLOYMENT_FILE_FULL_PATH}"

      - name: Commit and Push K8s YAML changes to Deployment Repo
        run: |
          cd deployment-repo
          
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@github.com"
          
          # Check if there are changes to the specific file to commit
          if ! git diff --quiet "${{ env.K8S_MANIFEST_PATH_IN_DEPLOY_REPO }}"; then
            echo "Changes detected in '${{ env.K8S_MANIFEST_PATH_IN_DEPLOY_REPO }}'. Committing..."
            git add "${{ env.K8S_MANIFEST_PATH_IN_DEPLOY_REPO }}"
            git commit -m "Update auth-service image to ${{ github.sha }} in K8s manifest

            Triggered by commit ${{ github.sha }} in ${{ github.repository }}"
            # Use the PAT for pushing
            git push https://${{ secrets.PAT_FOR_DEPLOYMENT_REPO }}@github.com/${{ env.DEPLOYMENT_REPO_OWNER_SLASH_NAME }}.git HEAD:main
            echo "Pushed updated K8s YAML to deployment repository."
          else
            echo "No changes to K8s YAML ('${{ env.K8S_MANIFEST_PATH_IN_DEPLOY_REPO }}') to commit."
          fi
